// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQi-N9xW2DGLOc2Esrd-o1dCJOxWv8eZM',
    appId: '1:573269413177:web:42a047e6b83061e747ece8',
    messagingSenderId: '573269413177',
    projectId: 'urbangenspark',
    authDomain: 'urbangenspark.firebaseapp.com',
    storageBucket: 'urbangenspark.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQi-N9xW2DGLOc2Esrd-o1dCJOxWv8eZM',
    appId: '1:573269413177:android:42a047e6b83061e747ece8',
    messagingSenderId: '573269413177',
    projectId: 'urbangenspark',
    authDomain: 'urbangenspark.firebaseapp.com',
    storageBucket: 'urbangenspark.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQi-N9xW2DGLOc2Esrd-o1dCJOxWv8eZM',
    appId: '1:573269413177:ios:42a047e6b83061e747ece8',
    messagingSenderId: '573269413177',
    projectId: 'urbangenspark',
    authDomain: 'urbangenspark.firebaseapp.com',
    storageBucket: 'urbangenspark.firebasestorage.app',
    iosBundleId: 'lb.urbanpoints.urbanPointsCustomer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQi-N9xW2DGLOc2Esrd-o1dCJOxWv8eZM',
    appId: '1:573269413177:macos:42a047e6b83061e747ece8',
    messagingSenderId: '573269413177',
    projectId: 'urbangenspark',
    authDomain: 'urbangenspark.firebaseapp.com',
    storageBucket: 'urbangenspark.firebasestorage.app',
    iosBundleId: 'lb.urbanpoints.urbanPointsCustomer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQi-N9xW2DGLOc2Esrd-o1dCJOxWv8eZM',
    appId: '1:573269413177:windows:42a047e6b83061e747ece8',
    messagingSenderId: '573269413177',
    projectId: 'urbangenspark',
    authDomain: 'urbangenspark.firebaseapp.com',
    storageBucket: 'urbangenspark.firebasestorage.app',
  );
}
